name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3 \
          python3-pip \
          python3-setuptools \
          git \
          zip \
          openjdk-17-jdk \
          unzip \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          pkg-config

    - name: Install Buildozer + Cython
      run: |
        pip install --upgrade pip Cython==0.29.33 setuptools
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-debug
        path: bin/*.apk
