name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3 \
          python3-pip \
          python3-setuptools \
          git \
          zip \
          openjdk-17-jdk \
          unzip \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          wget \
          pkg-config

    - name: Install Buildozer + Cython
      run: |
        pip install --upgrade pip Cython==0.29.33 setuptools
        pip install buildozer

    - name: Download Android SDK & NDK
      run: |
        mkdir -p $SDK_DIR
        curl -s https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $SDK_DIR
        mv $SDK_DIR/cmdline-tools $SDK_DIR/cmdline-tools-temp
        mkdir -p $SDK_DIR/cmdline-tools/latest
        mv $SDK_DIR/cmdline-tools-temp/* $SDK_DIR/cmdline-tools/latest
        yes | $SDK_DIR/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_DIR --licenses
        $SDK_DIR/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_DIR \
          "platform-tools" \
          "platforms;android-35" \
          "build-tools;35.0.0" \
          "ndk;25.2.9519653"
          
      
    - name: Set Android environment
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/Android" >> $GITHUB_ENV
        echo "PATH=$HOME/Android/cmdline-tools/cmdline-tools/bin:$HOME/Android/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-debug
        path: bin/*.apk
